version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - apt-get update
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
      - aws s3 rm s3://my-movies-app --recursive
      - aws s3 cp ./dist/css s3://my-movies-app/css --recursive
      - aws s3 cp ./dist/img s3://my-movies-app/img --recursive
      - aws s3 cp ./dist/js s3://my-movies-app/js --recursive
      - aws s3 cp ./dist/favicon.ico s3://my-movies-app/
      - aws s3 cp ./dist/index.html s3://my-movies-app/
